[package]
name = "imgui_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
imgui = "0.11.0"
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"
glium = "0.32.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 